baseURL = 'https://dev-vujut.linkkijkl.fi'
languageCode = 'fi-fi'
title = 'Linkki Jyväskylä ry 20v vuosijuhlat'
defaultContentLanguage = 'fi'

staticDir = ["static"]

disableKinds = ["taxonomy"]

[params]
    sponsors = "Yhteistyössä"
    sponsors-id = "sponsorit"
    organizer = "Linkki Jyväskylä ry"
    organizer-url = "https://linkkijkl.fi"
    header-subtext = "20v vuosijuhlat 20.3.2026"
