baseURL = 'https://dev-vujut.linkkijkl.fi'
languageCode = 'fi-fi'
title = 'Linkki Jyväskylä ry Vuosijuhlat 2025'

staticDir = ["static"]

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
